version: '3.8'

services:
  mlflow:
    build:
      context: mlflow
    container_name: mlflow_for_rest
    restart: unless-stopped
    ports:
      - "${MLFLOW_HOST_PORT}:${MLFLOW_DOCKER_PORT}"
  fastapi:
    build:
      context: fastapi
    container_name: fastapi
    environment:
      - production_model=ef7237e244a44992aff8e8a4b3979201
    ports:
      - "${REST_SERVICE_HOST_PORT}:${REST_SERVICE_DOCKER_PORT}"
    depends_on: [mlflow]
